# Generated by Django 5.1.1 on 2024-12-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0002_auto_20241220_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='times',
            new_name='times_field',
        ),
    ]
