# Generated by Django 5.1.1 on 2024-12-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0003_rename_times_task_times_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='times_field',
        ),
    ]
