# Generated by Django 5.1.1 on 2024-12-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0004_remove_task_times_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_as_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
