# Generated by Django 5.1.1 on 2024-12-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0005_task_updated_as_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_as_working',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
