# Generated by Django 5.1.1 on 2025-01-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0010_alter_project_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
