# Generated by Django 5.1.1 on 2024-12-21 07:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Loss Of pay', 'Loss Of pay'), ('Comp-Off', 'Comp-Off'), ('Sick Leave probation', 'Sick Leave probation'), ('Optional Holiday', 'Optional Holiday')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('session_from', models.CharField(choices=[('Session 1', 'Session 1'), ('Session 2', 'Session 2')], max_length=50)),
                ('session_to', models.CharField(choices=[('Session 1', 'Session 1'), ('Session 2', 'Session 2')], max_length=50)),
                ('reason', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_level', models.IntegerField(default=1)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('level1_approvers', models.ManyToManyField(blank=True, related_name='level1_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('level2_approvers', models.ManyToManyField(blank=True, related_name='level2_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('level3_approvers', models.ManyToManyField(blank=True, related_name='level3_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messagesytem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='message_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'png', 'txt'])])),
                ('reply_content', models.TextField(blank=True, null=True)),
                ('reply_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_shown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflowmanagementapp.messagesytem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
