# Generated by Django 5.1.1 on 2024-12-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesytem',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='messagesytem',
            name='reply_content',
        ),
        migrations.RemoveField(
            model_name='messagesytem',
            name='reply_from',
        ),
    ]
