# Generated by Django 5.1.1 on 2024-12-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0002_remove_messagesytem_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesytem',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='messagesytem',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagesytem',
            name='reply_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
