# Generated by Django 5.1.1 on 2024-12-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0003_messagesytem_message_id_messagesytem_reply_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesytem',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='workflowmanagementapp.messagesytem'),
        ),
    ]
