# Generated by Django 5.1.1 on 2024-12-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0005_emailtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTransaction',
        ),
    ]
