# Generated by Django 5.1.1 on 2024-12-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
        ('workflowmanagementapp', '0009_custommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_message', to='django_mailbox.message'),
        ),
    ]
