# Generated by Django 5.1.1 on 2024-12-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0011_custommessage_original_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesytem',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='messagesytem',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagesytem',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='CustomMessage',
        ),
        migrations.DeleteModel(
            name='Messagesytem',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
