# Generated by Django 5.1.1 on 2024-12-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0013_message_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repliess', related_query_name='replyess', to='workflowmanagementapp.message'),
        ),
    ]
