# Generated by Django 5.1.1 on 2025-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0016_group_groupmessage_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messageuploads/'),
        ),
    ]
