# Generated by Django 5.1.1 on 2025-01-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0019_chatloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audiofile',
            field=models.FileField(blank=True, null=True, upload_to='audiouploads/'),
        ),
    ]
