# Generated by Django 5.1.1 on 2025-01-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0020_message_audiofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audiofile',
        ),
    ]
