# Generated by Django 5.1.1 on 2025-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0025_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
