# Generated by Django 5.1.1 on 2025-01-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0026_groupmessage_is_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_individual',
            field=models.BooleanField(default=True),
        ),
    ]
