# Generated by Django 5.1.1 on 2025-01-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0028_groupmessage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
