# Generated by Django 5.1.1 on 2025-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowmanagementapp', '0030_groupmessage_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
