# Generated by Django 5.1.1 on 2025-01-29 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsapp', '0011_delete_event'),
        ('workflowmanagementapp', '0031_groupmessage_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('organiser', models.CharField(max_length=200)),
                ('partner', models.CharField(default='none', max_length=200)),
                ('partner_logo', models.URLField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
                ('actual_starttime', models.TimeField(null=True)),
                ('actual_endtime', models.TimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('actual_duration', models.DurationField(null=True)),
                ('agenda', models.JSONField(default=list)),
                ('remark', models.JSONField(default=list)),
                ('link', models.URLField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting', to='acsapp.project')),
            ],
        ),
    ]
